[build]
  command = "npm install --legacy-peer-deps && npm run build"
  commandOrigin = "config"
  publish = "/opt/build/repo/dist"
  publishOrigin = "config"

[build.environment]
  NODE_VERSION = "16"
  NPM_FLAGS = ""