build =
    command = npm install && npm run build
    commandOrigin = config

environment =
      - NODE_VERSION
      - NPM_FLAGS
    publish = /opt/build/repo/dist
    publishOrigin = config

plugins = 
    - inputs = {}
      origin = config
      package= '@netlify/plugin-parcel'